baseURL = "https://compassionate-meitner-44354d.netlify.app"
disableKinds = ["taxonomy", "taxonomyTerm"]
enableEmoji = true
ignoreErrors = ["error-remote-getjson"]
languageCode = "en-US"
pygmentsUseClasses = true
tags = ["personal", "homepage", "portfolio"]
theme = "osprey-delight"
title = "ACMC2021"
[Params]
author = "kdevo"
copyright = true
description = "Website landing page for Australasian Computer Music Conference 2021"
email = ""
enforceSinglePage = false
favicon = "favicon.png"
googleTagManager = ""
logoSmall = "favicon.png"
logoBig = "/images/acmc21-big.png"
opengraphImage = "/images/acmc21-logo.png"
tagline = "CONNECTIONS"
[Params.Contact]
select = ["generic", "coop", "business", "project"]
[Params.Feat]
ajaxBasin = ""
customCSS = false
googleTagManager = ""
lazyloading = true
structuredData = true
useBlog = true
useTermynal = true
[Params.Social]
# [[menu.main]]
# name = "Test"
# url = "#scholarly-paper"
# weight = 3
[[menu.main]]
name = "Call"
url = "#call"
weight = 2
[[menu.main]]
name = "About"
url = "#about"
weight = 1
